export enum ActionType {
  "CHANGE_PAGE",
  "TOGGLE_MODAL",
  "TOGGLE_MODAL_CREATOR",
  "ADD_TENDER",
  "REMOVE_TENDER",
  "SAVE_EDIT_TENDER",
  "EDITING_TENDER",
  "ENABLE_EDIT",
  "CANCEL_EDIT",
  "FILTER",
  "CHECK_CREATOR",
  "CANCLE_CHECK_CREATOR",
  "CREATE_TENDER_WITH_CREATOR"
}
